CREATE TABLE IF NOT EXISTS archived_video_formats (
    id INTEGER PRIMARY KEY,
    video_id INTEGER,
    abr DECIMAL,
    acodec TEXT,
    aspect_ratio DECIMAL,
    asr INTEGER,
    audio_channels INTEGER,
    audio_ext TEXT,
    columns INTEGER,
    container TEXT,
    duration INTEGER,
    dynamic_range TEXT,
    ext TEXT,
    filesize INTEGER,
    filesize_approx INTEGER,
    format TEXT,
    youtube_format_id TEXT,
    format_note TEXT,
    fps DECIMAL,
    has_drm BOOLEAN DEFAULT FALSE,
    height INTEGER,
    language TEXT,
    quality DECIMAL,
    resolution TEXT,
    rows INTEGER,
    source_preference INTEGER,
    stretched_ratio TEXT,
    tbr DECIMAL,
    vbr DECIMAL,
    vcodec TEXT,
    video_ext TEXT,
    width INTEGER,
    was_requested BOOLEAN DEFAULT FALSE,

    FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE,
    UNIQUE (video_id, youtube_format_id) ON CONFLICT IGNORE
);
